set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN H1 [get_ports {mc_data[0]}]
set_property PACKAGE_PIN K2 [get_ports {mc_data[1]}]
set_property PACKAGE_PIN H2 [get_ports {mc_data[2]}]
set_property PACKAGE_PIN G3 [get_ports {mc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[3]}]
set_property PACKAGE_PIN J1 [get_ports {mc_data[4]}]
set_property PACKAGE_PIN L2 [get_ports {mc_data[5]}]
set_property PACKAGE_PIN J2 [get_ports {mc_data[6]}]
set_property PACKAGE_PIN G2 [get_ports {mc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mc_data[7]}]
set_property PACKAGE_PIN J3 [get_ports mc_clk]
set_property PACKAGE_PIN K3 [get_ports mc_register_select]
set_property IOSTANDARD LVCMOS33 [get_ports mc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports mc_register_select]
set_property PACKAGE_PIN A14 [get_ports sound_out]
set_property IOSTANDARD LVCMOS33 [get_ports sound_out]
set_property PACKAGE_PIN N18 [get_ports {blueOut[0]}]
set_property PACKAGE_PIN L18 [get_ports {blueOut[1]}]
set_property PACKAGE_PIN K18 [get_ports {blueOut[2]}]
set_property PACKAGE_PIN J18 [get_ports {blueOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blueOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blueOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blueOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blueOut[3]}]
set_property PACKAGE_PIN J17 [get_ports {greenOut[0]}]
set_property PACKAGE_PIN H17 [get_ports {greenOut[1]}]
set_property PACKAGE_PIN G17 [get_ports {greenOut[2]}]
set_property PACKAGE_PIN D17 [get_ports {greenOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {greenOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {greenOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {greenOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {greenOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN G19 [get_ports {redOut[0]}]
set_property PACKAGE_PIN H19 [get_ports {redOut[1]}]
set_property PACKAGE_PIN J19 [get_ports {redOut[2]}]
set_property PACKAGE_PIN N19 [get_ports {redOut[3]}]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {redOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {redOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {redOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {redOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]





