# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hammi/OneDrive/Documenten/ShootingStar/GameEngine/ESP_Readout_VHDL/ESP_Readout_VHDL.srcs/sources_1/ip/RAMTHING/RAMTHING.xci
# IP: The module: 'RAMTHING' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hammi/OneDrive/Documenten/ShootingStar/GameEngine/ESP_Readout_VHDL/ESP_Readout_VHDL.srcs/sources_1/ip/RAMTHING/RAMTHING_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAMTHING'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/hammi/OneDrive/Documenten/ShootingStar/GameEngine/ESP_Readout_VHDL/ESP_Readout_VHDL.srcs/sources_1/ip/RAMTHING/RAMTHING.xci
# IP: The module: 'RAMTHING' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hammi/OneDrive/Documenten/ShootingStar/GameEngine/ESP_Readout_VHDL/ESP_Readout_VHDL.srcs/sources_1/ip/RAMTHING/RAMTHING_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAMTHING'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
